### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by Jenus** [RxSwiftCommunity/RxGoogleMaps#8]
Hi,  what is the milestone of Swift 4 support?

**Comment by GabrielAraujo** [comment]
https://github.com/RxSwiftCommunity/RxGoogleMaps/pull/9

**Comment by freak4pc** [comment]
Fixed by #9

**Comment by olbartek** [comment]
I think you need to push `2.5.0` tag with the swift4.0 support. Right now installation fails through CocoaPods, because version 2.5.0 is not found. 
I can only install library through CocoaPods like this:
`pod 'RxGoogleMaps', :git => 'https://github.com/RxSwiftCommunity/RxGoogleMaps.git', :branch => 'master'`

**Comment by freak4pc** [comment]
@olbartek We're aware of that. Unfortunately the original author of this CocoaPod isn't replying. I've been trying to reach him here: https://github.com/RxSwiftCommunity/RxGoogleMaps/pull/9#issuecomment-341930157

We're trying to resolve this kind of situation in https://github.com/RxSwiftCommunity/contributors/issues/29 but for now we'll have to try and manually reach the author. 

The approach to manually add the repo and branch to your Podfile is the correct approach to take for now.
